### ISSUE TITLE
Choosing the Dataset 

### ISSUE THREAD

**Issue by rachelywong** [UBC-MDS/dash_of_spice#1]
Come up with 1-2 ideas for our dataset for our upcoming discussion.

**Comment by ChadNeald** [comment]
Here are some brainstorming datasets that I found if we are interested:

- Spotify Songs Data: We've worked with this dataset or something very similar to it in our ML course.
https://www.kaggle.com/yamaerenay/spotify-dataset-19212020-160k-tracks?select=data.csv

- Ramen Ratings. Different ramen products are rated and reviewed by country, brand, style, etc. There are only 5 or 6 different columns to use however which could be limiting.
https://www.kaggle.com/residentmario/ramen-ratings?select=ramen-ratings.csv

- Netflix shows. Data on different shows and movies added to Netflix including the data, country where created, actors/actresses, etc.
https://www.kaggle.com/shivamb/netflix-shows

- World Happiness Data. Happiness is ranked by country with other factors listed such as freedom, trust, and health ratings.
https://www.kaggle.com/unsdsn/world-happiness

**Comment by rachelywong** [comment]
I also looked into the world happiness data! They have years from 2015 up to 2020.

Here are some other datasets I found that were pretty interesting:

- Bob Ross Paintings Analysis: Just a super cute dataset about presence of different subjects (trees, rocks, clouds, etc.) in his artwork. https://github.com/fivethirtyeight/data/tree/master/bob-ross 

- Drug Use by Age: Interesting dataset with many different features based on a variety of different drugs. https://github.com/fivethirtyeight/data/tree/master/drug-use-by-age

- Mushroom Classification: This dataset is very similar to other datasets we've worked on in our ML courses, and would work well if we wanted to apply some ML to our project. There are a bunch of different features for us to work with as well. https://www.kaggle.com/uciml/mushroom-classification

**Comment by cmmclaug** [comment]
The one I had brought up originally:
Developer Survey Results:
https://insights.stackoverflow.com/survey/2019

If only this one had a map: 
Employment statistics by major:
https://github.com/fivethirtyeight/data/tree/master/college-majors

**Comment by Saule-Atymtayeva** [comment]
My suggestions are:

World University Rankings 2020
https://www.kaggle.com/joeshamen/world-university-rankings-2020?select=Word_University_Rank_2020.csv


Crime in Vancouver
https://www.kaggle.com/wosaku/crime-in-vancouver

**Comment by rachelywong** [comment]
world happiness report
https://www.kaggle.com/mathurinache/world-happiness-report

**Comment by rachelywong** [comment]
We have decided to go with the World Happiness Report Dataset (https://www.kaggle.com/mathurinache/world-happiness-report).
