### ISSUE TITLE
Submission

### ISSUE THREAD

**Issue by rachelywong** [UBC-MDS/dash_of_spice#10]

**Comment by rachelywong** [comment]
Canvas submission

Once you have finished the write up of the dashboard proposal and the team-working documents, you must create a release on GitHub.com before the submission deadline.
Please read the GitHub documentation on how to create a release via the online interface. Name your release with the respective milestone name.
We will grade all files in the repo at the state they were in when you created the release. This means that you can continue to make changes in the repo without worrying about messing up your grading for the previous milestone.
The only file you need to submit to Canvas is the one called canvas-submission.md.
This file is in your github.ubc.ca repo.
Submit this file manually on Canvas and only once per group.
Make sure to add a link to your milestone release in this file and leave the rest as is (this facilitates grading).


Just waiting on a lil app demo to submit

**Comment by ChadNeald** [comment]
Milestone 1 submitted.
