### ISSUE TITLE
Layout of all widgets

### ISSUE THREAD

**Issue by ChadNeald** [UBC-MDS/dash_of_spice#29]

**Comment by ChadNeald** [comment]
Style, formatting, and colour scheme.

**Comment by ChadNeald** [comment]
Your interface should be as self-documenting as possible, with appropriate labels for panes and widgets, legends documenting the meaning of visual encodings, and a meaningful title for the app.
Note that TAs will be grading your app on Heroku in a full-screen window

**Comment by rachelywong** [comment]
dddoonnee!
