### ISSUE TITLE
Sliders Based on Rankings

### ISSUE THREAD

**Issue by ChadNeald** [UBC-MDS/dash_of_spice#30]
- add a toggle button
- add a reset button

**Comment by rachelywong** [comment]
hi i’m very proud of my work LOL even though it looks janky I currently have a working ranking section that will update and filter the countries list, and a reset button

the filter basically sorts the importances the user inputted and then sorts the countries based on the top importance (very basic filtering system, will try to improve this)

![Screen Shot 2021-01-19 at 6 14 31 PM](https://user-images.githubusercontent.com/45707735/105118274-f1911e80-5a82-11eb-80e6-95866c5fc707.png)

**Comment by rachelywong** [comment]
done
