### ISSUE TITLE
Reflection

### ISSUE THREAD

**Issue by ChadNeald** [UBC-MDS/dash_of_spice#34]
Reflect on what you think your dashboard does well what its limitations are, and what are good future improvements and additions. This section should not be more than 500 words and the reflection-milestone2.md document should live in your GitHub.com repo in the doc folder.

**Comment by rachelywong** [comment]
- filtering the data based on so many rankings is difficult
- plots seem complicated, especially to have one for each feature and if we're analyzing 100+ countries on a bar graph it gets super complicated
- might be best to just to show the top 5 countries
- dataset needs a lot of processing (combining the years, making sure the column names from each csv are correct, duplicate or missing values for countries)

**Comment by rachelywong** [comment]
Dashboard Strengths:
- user rankings of features is connected to the top 5 country list
- users can rank which feature is most important to them and the countries suggested will be sorted by their desired feature 
- map is connected to the plots, we can visualize which country relates to the plots, nice looking
- plots show a progression of the specified country’s stats throughout the years, compared to a global average
- users have the ability to choose which feature stat they would like to see for the country using a simple dropdown menu, this better highlights the plot for the specified feature

Dashboard Limitations:
- algorithm to calculate happiness score based on user rankings of features
- ability to click country on map to show that country’s stats
- ability to choose which year we want to see the data from, as well as a progression of data throughout the years
- give happiness score?

What I have so far:

# Milestone 2 Reflection

### Implementations
Our interactive dashboard allows users to rank the importance of different features (such as health and economy), and provide them with the top five countries worldwide that align most with our user’s values. 

### Dashboard Strengths
The dashboard has easy to use sliders to rank different features related to calculating overall happiness of living in a certain country. These sliders are connected directly to the top five country list, and there is a reset button to clear any inputs.

### Dashboard Limitations

### Future Improvements and Additions

**Comment by cmmclaug** [comment]
One issue I ran into was when trying to clean the country data to match the maps with their countries.

A lot of countries weren't listed or were listed differently because of political reasons. For example Kosovo was listed in world happiness, but not in the map shapes. Some googling showed this was because this is still a disputed territory without a political consensus. It was weird to consider my data cleaning might be making ignorant decisions about thorny political issues.

**Comment by CraigEnsemble** [comment]
For Dashboard limitations, the inability of the map to provide click callbacks really limits the interactivity to only coming from other altair plots and not updating dash components.

**Comment by cmmclaug** [comment]
For Dashboard limitations, the inability of the map to provide click callbacks really limits the interactivity to only coming from other Altair plots and not updating dash components. Also not being able to pan/zoom on Altair maps!

**Comment by rachelywong** [comment]
done
