### ISSUE TITLE
Milestone 1 feedback

### ISSUE THREAD

**Issue by ghost** [UBC-MDS/dash_of_spice#37]
Hey Group 5,

Congrats on finishing milestone 1! You're off to a good start. Your proposal was well written overall. It provided a clear outline of your purpose and goals. There were a few minor grammatical errors and some run-on sentences, so you should be sure to proofread a bit more thoroughly in the future to avoid this.

With regards to your dashboard:
- The general layout looks good, though complexity could be reduced somewhat for milestone 2
- Map and search bar aesthetic is nice and that map can provide a canvas for later functionality if you have time and deem it useful
- I'd recommend reducing the number of plots at the bottom . Particularly if they are going to contain 153 bars, as having five such plots would be rather cramped. If you want more plots later, a scroll bar may not be the best option. It's very constraining (can't change the order) and hides the available options.
- From your description, you would probably *only* have bar graphs at the bottom, not scatter plots or other trend lines since you aren't relating two continuous variables. Perhaps you could show yearly trends for the selected countries if you want those types of plots. Of course, in such a case you'd remove the year buttons at the top. 
- Do you really want a list of 153 countries to be scrollable? That will take a long time to scroll. I would reconsider how you show this info. A long list is rarely the best way.

**Comment by rachelywong** [comment]
Thank you, Chris! We have taken your feedback into consideration :)
