### ISSUE TITLE
Milestone 2 Feedback

### ISSUE THREAD

**Issue by ghost** [UBC-MDS/dash_of_spice#56]
Hey Group 5, congrats on finishing milestone 2! You've planned an ambitious dashboard, but I think you're off to a solid start. While your dashboard is clearly still a work in progress, I really like the concept and I'm excited to see the end-product. Overall, I think the layout is clear and usability is great (minus a few bugs). Your reflection addresses some of my thoughts already, but here are a few additional points I think could be fixed/improved:
- selecting a lot of countries makes the dropdown go under the map, also some selections make that iframe have scroll bars
- map related things:
  - map and dropdown selections aren't linked
  - changing sliders reselects the default countries rather than keeping what was just selected
  - changing sliders doesn't change map scores(?)
- when the dropdown is empty, but map has selections, the plot at the bottom is still gone
- I think it would be really cool, if I could see the happiness score as a composite of it's components via some stacked graph or similar. Perhaps this could be a series of horizontal bars replacing the rank table (but of the same proportions and with name and rank written on the bar, not the y-axis)
- unclear what "rank" in top 10 countries table is

Also, with regards to the README component:
- Could use updated images or gifs. You also forgot to include info on setting up and running the app (this isn't currently in either your README or the CONTRIBUTING file that you link)

**Comment by rachelywong** [comment]
Hi Chris!

Thank you for the feedback, we have addressed all of these suggestions!

Specifically:
- Properly aligned all dropdowns
- Implemented callbacks to make sure all selections and clicks by the user work properly
- Plots have been defaulted and work now with user selections
- Different metrics can be selected to be compared on a line plot now! With a global average and the ability to compare different countries
- Rank has been defined above the table
- Updated gif and info on setting up and running the app has been added!

You can check out our new app [here](https://happy-navvy-r.herokuapp.com/) or from our new GitHub page [here](https://github.com/UBC-MDS/dash_of_spice-R)
